# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm install cypress --save-dev

  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run guest:bonefishgrill_tests
  displayName: 'run cypress'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run merge:reports
  displayName: 'merge reports'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'automation-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'